# Generated by Django 5.1.4 on 2025-01-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarea', '0002_alter_category_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technologies'),
        ),
    ]
